const SECRET_RULES = [
  { kind: "private_key_block", label: "Private Key Block", severity: 6, confidence: "high", regex: /-----BEGIN [A-Z ]*PRIVATE KEY-----[\s\S]{40,}?-----END [A-Z ]*PRIVATE KEY-----/g },
  { kind: "aws_access_key_id", label: "AWS Access Key ID", severity: 5, confidence: "high", regex: /\bAKIA[0-9A-Z]{16}\b/g },
  { kind: "aws_session_token", label: "AWS Session Token", severity: 5, confidence: "high", regex: /\b(?:x-amz-security-token|aws[_-]?session[_-]?token)\b\s*[:=]\s*['"`]?([A-Za-z0-9\/+=._-]{16,})['"`]?/gi, captureGroup: 1 },
  { kind: "google_api_key", label: "Google API Key", severity: 5, confidence: "high", regex: /\bAIza[0-9A-Za-z\-_]{35}\b/g },
  { kind: "github_token", label: "GitHub Token", severity: 5, confidence: "high", regex: /\bgh[pousr]_[A-Za-z0-9_]{20,255}\b/g },
  { kind: "slack_token", label: "Slack Token", severity: 5, confidence: "high", regex: /\bxox[baprs]-[A-Za-z0-9-]{10,}\b/g },
  { kind: "stripe_secret", label: "Stripe Secret Key", severity: 5, confidence: "high", regex: /\bsk_(?:live|test)_[A-Za-z0-9]{16,}\b/g },
  { kind: "stripe_restricted", label: "Stripe Restricted Key", severity: 5, confidence: "high", regex: /\brk_(?:live|test)_[A-Za-z0-9]{16,}\b/g },
  { kind: "openai_key", label: "OpenAI API Key", severity: 5, confidence: "high", regex: /\b(sk-(?:proj-)?[A-Za-z0-9_-]{20,})\b/g, captureGroup: 1 },
  { kind: "discord_token", label: "Discord Token", severity: 5, confidence: "high", regex: /\b[MN][A-Za-z\d]{23}\.[A-Za-z\d_-]{6}\.[A-Za-z\d_-]{27}\b/g },
  { kind: "twilio_sid", label: "Twilio Account SID", severity: 4, confidence: "medium", regex: /\bAC[0-9a-fA-F]{32}\b/g },
  { kind: "jwt", label: "JWT", severity: 3, confidence: "medium", regex: /\beyJ[a-zA-Z0-9_-]{8,}\.[a-zA-Z0-9._-]{8,}\.[a-zA-Z0-9._-]{8,}\b/g },
  { kind: "basic_auth_url", label: "Credentialed URL", severity: 5, confidence: "high", regex: /\b[a-z][a-z0-9+.-]*:\/\/[^/\s:@]+:[^@\s]+@[^/\s]+/gi },
  { kind: "db_uri", label: "Credentialed DB URI", severity: 5, confidence: "high", regex: /\b(?:mongodb(?:\+srv)?|postgres(?:ql)?|mysql|redis):\/\/[^/\s]+:[^@\s]+@[^/\s]+/gi },
  { kind: "basic_auth_header", label: "Basic Auth Header", severity: 5, confidence: "medium", regex: /\bauthorization\b\s*:\s*basic\s+([A-Za-z0-9+/=]{8,})/gi, captureGroup: 1 },
  { kind: "context_secret", label: "Contextual Secret", severity: 4, confidence: "medium", regex: /\b(?:api[_-]?key|apikey|client[_-]?secret|clientSecret|access[_-]?token|accessToken|refresh[_-]?token|refreshToken|secret|token|password|passwd|private[_-]?key|x-api-key|x-api-token|authorization)\b\s*[:=]\s*['"`]?([A-Za-z0-9\/+=._:-]{8,256})['"`]?/gi, captureGroup: 1 },
  { kind: "aws_context_secret", label: "AWS Secret Key", severity: 5, confidence: "high", regex: /\baws[_-]?secret[_-]?access[_-]?key\b\s*[:=]\s*['"`]?([A-Za-z0-9\/+=._-]{16,})['"`]?/gi, captureGroup: 1 },
  { kind: "api_token_context", label: "API Token", severity: 4, confidence: "medium", regex: /\b(?:api[_-]?token|access[_-]?token|refresh[_-]?token|bearer|token)\b\s*[:=]\s*['"`]?([A-Za-z0-9\/+=._-]{12,256})['"`]?/gi, captureGroup: 1 },
  { kind: "webhook_url", label: "Webhook URL", severity: 4, confidence: "medium", regex: /https:\/\/hooks\.slack\.com\/services\/T[A-Z0-9]{8,}\/B[A-Z0-9]{8,}\/[A-Za-z0-9]{20,}/g },
  { kind: "firebase_credential", label: "Firebase Credential", severity: 4, confidence: "medium", regex: /(?:apiKey|authDomain|databaseURL|projectId|storageBucket|messagingSenderId|appId)\s*[:=]\s*['"`]([^'"`]{10,})['"`]/gi, captureGroup: 1 },
  { kind: "sendgrid_key", label: "SendGrid API Key", severity: 5, confidence: "high", regex: /\bSG\.[A-Za-z0-9_-]{22,}\.[A-Za-z0-9_-]{22,}\b/g },
  { kind: "anthropic_key", label: "Anthropic API Key", severity: 5, confidence: "high", regex: /\b(sk-ant-(?:api[0-9]+-)?[A-Za-z0-9_-]{24,})\b/g, captureGroup: 1 },
  { kind: "mailgun_key", label: "Mailgun API Key", severity: 5, confidence: "high", regex: /\b(key-[a-f0-9]{32})\b/g, captureGroup: 1 },
  { kind: "huggingface_token", label: "HuggingFace Token", severity: 4, confidence: "medium", regex: /\b(hf_[A-Za-z0-9]{20,})\b/g, captureGroup: 1 },
  { kind: "linear_api_key", label: "Linear API Key", severity: 4, confidence: "medium", regex: /\b(lin_api_[a-f0-9]{32})\b/g, captureGroup: 1 },
  { kind: "supabase_service_role", label: "Supabase Service Role Key", severity: 5, confidence: "high", regex: /\beyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9\.[A-Za-z0-9_-]{100,}\.(?:[A-Za-z0-9_-]{43,})\b/g },
];
module.exports = { SECRET_RULES };
